name: pull_request_target run

on:
  pull_request_target:
    types: [opened, synchronize, edited]

jobs:
  pr-check: 
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: echo 'PR checked!'
