name: Pull Request Check

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Branch
        run: ./check_branch_name.sh ${{ github.head_ref }}
