name: E2E

on: [push, pull_request_target]

jobs:
  cypress-matrix:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code (pull_request)
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.number }}/merge'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install npm dependencies
        uses: apache-superset/cached-dependencies@v1.1
        with:
          run: |
            npm-install
      
