name: pull_request_target run

on:
  pull_request_target:
    types: [opened, synchronize, edited]

jobs:
  pr-check: 
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - name: Setup Action
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: a docker action
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'XXXXXXXXXXX'
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: another job
        run: id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Changed Files Exporter
        if: github.event_name == 'pull_request_target'
        id: files
        uses: futuratrepadeira/changed-files@v3.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
