name: Example workflow
on:
  workflow_dispatch   
permissions:
      id-token: write
      contents: read
jobs:
  off_the_cliff_we_go:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::142069644989:role/fxa-content-cdn-stage-asset-upload
          role-session-name: CDNAssetUpload
      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity
