name: Example workflow
on:
  workflow_dispatch   
permissions:
      id-token: write
      contents: read
jobs:
  off_the_cliff_we_go:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::126027368216:role/tf-teleport-ami-gha-role
          aws-region: us-west-2
          role-session-name: gha-update-ami-ids-1
      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity
